import 'package:flutter/widgets.dart';

/// Flutter icons FlexIcons.
///
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlexIcons
///      fonts:
///       - asset: fonts/FlexIcons.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
class FlexIcons {
  FlexIcons._();

  static const String _kFontFam = 'FlexIcons';
  static const String? _kFontPkg = null;

  static const IconData infinity =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple =
      IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windows =
      IconData(0xf17a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linux =
      IconData(0xf17c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
