import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

/// The [AppTheme] defines light and dark themes for the app.
///
/// Theme setup for FlexColorScheme package v8.
/// Use same major flex_color_scheme package version. If you use a
/// lower minor version, some properties may not be supported.
/// In that case, remove them after copying this theme to your
/// app or upgrade package to version 8.0.0-dev.1.
///
/// Use in [MaterialApp] like this:
///
/// MaterialApp(
///  theme: AppTheme.light,
///  darkTheme: AppTheme.dark,
///  :
/// );
sealed class AppTheme {
  // The defined light theme.
  static ThemeData light = FlexThemeData.light(
    scheme: FlexScheme.amber,
    surfaceMode: FlexSurfaceMode.highBackgroundLowScaffold,
    blendLevel: 4,
    appBarStyle: FlexAppBarStyle.primary,
    appBarOpacity: 0.90,
    appBarElevation: 0.5,
    bottomAppBarElevation: 1.0,
    tabBarStyle: FlexTabBarStyle.forAppBar,
    lightIsWhite: true,
    swapColors: true,
    tooltipsMatchBackground: true,
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      tintedDisabledControls: true,
      blendOnLevel: 4,
      blendOnColors: true,
      useM2StyleDividerInM3: true,
      thinBorderWidth: 0.5,
      thickBorderWidth: 1.5,
      adaptiveSplash: FlexAdaptive.apple(),
      splashTypeAdaptive: FlexSplashType.instantSplash,
      adaptiveRemoveElevationTint: FlexAdaptive.all(),
      adaptiveElevationShadowsBack: FlexAdaptive.all(),
      adaptiveAppBarScrollUnderOff: FlexAdaptive.apple(),
      adaptiveRadius: FlexAdaptive.apple(),
      adaptiveDialogRadius: FlexAdaptive.apple(),
      defaultRadius: 8.0,
      defaultRadiusAdaptive: 10.0,
      textButtonRadius: 5.0,
      textButtonSchemeColor: SchemeColor.primaryFixedDim,
      filledButtonRadius: 3.0,
      elevatedButtonRadius: 1.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      outlinedButtonRadius: 4.0,
      outlinedButtonSchemeColor: SchemeColor.tertiary,
      outlinedButtonOutlineSchemeColor: SchemeColor.tertiary,
      outlinedButtonBorderWidth: 0.5,
      outlinedButtonPressedBorderWidth: 3.0,
      toggleButtonsRadius: 5.0,
      toggleButtonsSchemeColor: SchemeColor.primaryContainer,
      toggleButtonsSelectedForegroundSchemeColor:
          SchemeColor.onPrimaryContainer,
      toggleButtonsUnselectedSchemeColor: SchemeColor.primary,
      toggleButtonsBorderWidth: 0.5,
      segmentedButtonRadius: 10.0,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonSelectedForegroundSchemeColor:
          SchemeColor.onPrimaryContainer,
      segmentedButtonUnselectedSchemeColor: SchemeColor.onSecondary,
      segmentedButtonUnselectedForegroundSchemeColor: SchemeColor.secondary,
      segmentedButtonBorderWidth: 1.0,
      switchSchemeColor: SchemeColor.primaryContainer,
      switchThumbSchemeColor: SchemeColor.onPrimary,
      switchThumbFixedSize: true,
      switchAdaptiveCupertinoLike: FlexAdaptive.apple(),
      checkboxSchemeColor: SchemeColor.primaryContainer,
      radioSchemeColor: SchemeColor.primaryContainer,
      unselectedToggleIsColored: true,
      sliderBaseSchemeColor: SchemeColor.primaryContainer,
      sliderValueTinted: true,
      sliderValueIndicatorType: FlexSliderIndicatorType.rectangular,
      sliderShowValueIndicator: ShowValueIndicator.always,
      sliderTrackHeight: 6.0,
      inputDecoratorSchemeColor: SchemeColor.primary,
      inputDecoratorIsFilled: true,
      inputDecoratorIsDense: true,
      inputDecoratorBackgroundAlpha: 14,
      inputDecoratorBorderSchemeColor: SchemeColor.primary,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorRadius: 10.0,
      inputDecoratorUnfocusedHasBorder: false,
      inputDecoratorFocusedBorderWidth: 1.0,
      inputDecoratorPrefixIconSchemeColor: SchemeColor.onPrimaryFixedVariant,
      listTileSelectedSchemeColor: SchemeColor.onTertiary,
      listTileIconSchemeColor: SchemeColor.onSurface,
      listTileTextSchemeColor: SchemeColor.onPrimaryContainer,
      listTileTileSchemeColor: SchemeColor.surfaceContainerLowest,
      listTileSelectedTileSchemeColor: SchemeColor.primary,
      listTileContentPadding: EdgeInsetsDirectional.fromSTEB(13, 4, 6, 4),
      listTileHorizontalTitleGap: 8.0,
      listTileMinVerticalPadding: 5.0,
      listTileStyle: ListTileStyle.drawer,
      listTileTitleAlignment: ListTileTitleAlignment.titleHeight,
      fabUseShape: true,
      fabAlwaysCircular: true,
      fabSchemeColor: SchemeColor.tertiary,
      fabForegroundSchemeColor: SchemeColor.tertiaryContainer,
      chipRadius: 17.0,
      chipFontSize: 11.0,
      chipIconSize: 18.0,
      chipPadding: EdgeInsetsDirectional.fromSTEB(3, 3, 3, 3),
      cardRadius: 5.0,
      popupMenuRadius: 2.0,
      popupMenuElevation: 8.0,
      popupMenuSchemeColor: SchemeColor.surfaceContainerHigh,
      popupMenuOpacity: 0.98,
      alignedDropdown: true,
      tooltipRadius: 16.0,
      dialogBackgroundSchemeColor: SchemeColor.primaryFixed,
      dialogElevation: 2.0,
      dialogRadius: 33.0,
      dialogRadiusAdaptive: 8.0,
      useInputDecoratorThemeInDialogs: true,
      timePickerDialogRadius: 3.0,
      timePickerElementRadius: 10.0,
      datePickerDialogRadius: 4.0,
      datePickerHeaderBackgroundSchemeColor: SchemeColor.primary,
      datePickerDividerSchemeColor: SchemeColor.secondary,
      snackBarRadius: 9.0,
      snackBarElevation: 3.0,
      snackBarBackgroundSchemeColor: SchemeColor.onPrimaryContainer,
      snackBarActionSchemeColor: SchemeColor.primaryFixed,
      appBarScrolledUnderElevation: 6.0,
      appBarCenterTitle: true,
      bottomAppBarSchemeColor: SchemeColor.surfaceContainerHighest,
      bottomAppBarHeight: 72.0,
      tabBarUnselectedItemOpacity: 0.69,
      tabBarIndicatorWeight: 6.5,
      tabBarIndicatorTopRadius: 4.5,
      tabBarDividerColor: Color(0x00000000),
      tabBarTabAlignment: TabAlignment.start,
      drawerRadius: 8.0,
      drawerElevation: 4.0,
      drawerBackgroundSchemeColor: SchemeColor.surfaceContainerHighest,
      drawerWidth: 300.0,
      drawerIndicatorWidth: 281.0,
      drawerIndicatorRadius: 10.0,
      drawerIndicatorSchemeColor: SchemeColor.primaryContainer,
      drawerIndicatorOpacity: 0.9,
      drawerSelectedItemSchemeColor: SchemeColor.primary,
      drawerUnselectedItemSchemeColor: SchemeColor.onPrimaryContainer,
      bottomSheetBackgroundColor: SchemeColor.tertiaryContainer,
      bottomSheetModalBackgroundColor: SchemeColor.primaryFixed,
      bottomSheetRadius: 30.0,
      bottomSheetElevation: 4.0,
      bottomSheetModalElevation: 3.0,
      bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.onPrimaryFixed,
      bottomNavigationBarMutedUnselectedLabel: true,
      bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
      bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.onPrimaryFixed,
      bottomNavigationBarMutedUnselectedIcon: true,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.surfaceContainer,
      bottomNavigationBarSelectedLabelSize: 12,
      bottomNavigationBarUnselectedLabelSize: 10,
      bottomNavigationBarSelectedIconSize: 22,
      bottomNavigationBarUnselectedIconSize: 19,
      menuRadius: 7.0,
      menuElevation: 6.0,
      menuSchemeColor: SchemeColor.surfaceContainerHighest,
      menuOpacity: 0.89,
      menuPadding: EdgeInsetsDirectional.fromSTEB(2.0, 3.0, 4.0, 3.0),
      menuBarBackgroundSchemeColor: SchemeColor.tertiary,
      menuBarRadius: 0.0,
      menuBarElevation: 0.0,
      menuBarShadowColor: Color(0x00000000),
      menuItemBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
      menuItemForegroundSchemeColor: SchemeColor.onSurfaceVariant,
      menuIndicatorBackgroundSchemeColor: SchemeColor.secondary,
      searchBarElevation: 2.0,
      searchViewElevation: 2.0,
      searchBarRadius: 5.0,
      searchViewRadius: 5.0,
      searchViewHeaderHeight: 67.0,
      searchUseGlobalShape: true,
      navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      navigationBarUnselectedLabelSchemeColor: SchemeColor.onPrimaryContainer,
      navigationBarMutedUnselectedLabel: true,
      navigationBarSelectedIconSchemeColor: SchemeColor.secondary,
      navigationBarUnselectedIconSchemeColor: SchemeColor.onPrimaryContainer,
      navigationBarMutedUnselectedIcon: true,
      navigationBarIndicatorSchemeColor: SchemeColor.primary,
      navigationBarIndicatorOpacity: 0.76,
      navigationBarIndicatorRadius: 6.0,
      navigationBarBackgroundSchemeColor: SchemeColor.tertiaryFixed,
      navigationBarOpacity: 0.96,
      navigationBarElevation: 8.0,
      navigationBarHeight: 69.0,
      navigationBarLabelBehavior:
          NavigationDestinationLabelBehavior.onlyShowSelected,
      navigationBarSelectedLabelSize: 12,
      navigationBarUnselectedLabelSize: 10,
      navigationBarSelectedIconSize: 25,
      navigationBarUnselectedIconSize: 22,
      adaptiveRemoveNavigationBarTint: FlexAdaptive.all(),
      navigationRailSelectedLabelSchemeColor: SchemeColor.secondary,
      navigationRailUnselectedLabelSchemeColor: SchemeColor.onPrimaryContainer,
      navigationRailSelectedIconSchemeColor: SchemeColor.secondary,
      navigationRailUnselectedIconSchemeColor: SchemeColor.onPrimaryContainer,
      navigationRailUseIndicator: true,
      navigationRailIndicatorSchemeColor: SchemeColor.primary,
      navigationRailIndicatorOpacity: 0.81,
      navigationRailIndicatorRadius: 9.0,
      navigationRailBackgroundSchemeColor: SchemeColor.primaryFixed,
      navigationRailOpacity: 0.85,
      navigationRailElevation: 9.0,
      navigationRailLabelType: NavigationRailLabelType.all,
      navigationRailSelectedLabelSize: 13,
      navigationRailUnselectedLabelSize: 12,
      navigationRailSelectedIconSize: 22,
      navigationRailUnselectedIconSize: 20,
      navigationRailGroupAlignment: -0.60,
      navigationRailMinWidth: 86,
      navigationRailMinExtendedWidth: 214,
    ),
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
      useError: true,
      useExpressiveOnContainerColors: true,
      useLegacyMonochromeSeedBehavior: true,
    ),
    tones: FlexSchemeVariant.chroma
        .tones(Brightness.light)
        .higherContrastFixed()
        .monochromeSurfaces()
        .onMainsUseBW()
        .onSurfacesUseBW()
        .surfacesUseBW(),
    visualDensity: VisualDensity.compact,
    materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    swapLegacyOnMaterial3: true,
  );
  // The defined dark theme.
  static ThemeData dark = FlexThemeData.dark(
    scheme: FlexScheme.amber,
    surfaceMode: FlexSurfaceMode.highScaffoldLowSurface,
    blendLevel: 4,
    tabBarStyle: FlexTabBarStyle.forAppBar,
    tooltipsMatchBackground: true,
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      tintedDisabledControls: true,
      blendOnLevel: 4,
      blendOnColors: true,
      useM2StyleDividerInM3: true,
      adaptiveSplash: FlexAdaptive.apple(),
      splashTypeAdaptive: FlexSplashType.instantSplash,
      adaptiveRadius: FlexAdaptive.apple(),
      adaptiveDialogRadius: FlexAdaptive.apple(),
      defaultRadius: 8.0,
      defaultRadiusAdaptive: 10.0,
      thinBorderWidth: 0.5,
      thickBorderWidth: 1.5,
      textButtonRadius: 5.0,
      textButtonSchemeColor: SchemeColor.primaryFixedDim,
      filledButtonRadius: 3.0,
      elevatedButtonRadius: 1.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
      elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
      outlinedButtonRadius: 4.0,
      outlinedButtonSchemeColor: SchemeColor.tertiary,
      outlinedButtonOutlineSchemeColor: SchemeColor.tertiary,
      outlinedButtonBorderWidth: 0.5,
      outlinedButtonPressedBorderWidth: 3.0,
      toggleButtonsRadius: 5.0,
      toggleButtonsSchemeColor: SchemeColor.primaryContainer,
      toggleButtonsSelectedForegroundSchemeColor:
          SchemeColor.onPrimaryContainer,
      toggleButtonsUnselectedSchemeColor: SchemeColor.primary,
      toggleButtonsBorderWidth: 0.5,
      segmentedButtonRadius: 10.0,
      segmentedButtonSchemeColor: SchemeColor.primary,
      segmentedButtonSelectedForegroundSchemeColor:
          SchemeColor.onPrimaryContainer,
      segmentedButtonUnselectedSchemeColor: SchemeColor.onSecondary,
      segmentedButtonUnselectedForegroundSchemeColor: SchemeColor.secondary,
      segmentedButtonBorderWidth: 1.0,
      switchSchemeColor: SchemeColor.primaryContainer,
      switchThumbSchemeColor: SchemeColor.onPrimary,
      switchThumbFixedSize: true,
      switchAdaptiveCupertinoLike: FlexAdaptive.apple(),
      checkboxSchemeColor: SchemeColor.primaryContainer,
      radioSchemeColor: SchemeColor.primaryContainer,
      unselectedToggleIsColored: true,
      sliderBaseSchemeColor: SchemeColor.primaryContainer,
      sliderValueTinted: true,
      sliderValueIndicatorType: FlexSliderIndicatorType.rectangular,
      sliderShowValueIndicator: ShowValueIndicator.always,
      sliderTrackHeight: 6.0,
      inputDecoratorSchemeColor: SchemeColor.primary,
      inputDecoratorIsFilled: true,
      inputDecoratorIsDense: true,
      inputDecoratorBackgroundAlpha: 45,
      inputDecoratorBorderSchemeColor: SchemeColor.primary,
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorRadius: 10.0,
      inputDecoratorUnfocusedHasBorder: false,
      inputDecoratorFocusedBorderWidth: 1.0,
      inputDecoratorPrefixIconSchemeColor: SchemeColor.primaryFixed,
      inputCursorSchemeColor: SchemeColor.primaryContainer,
      inputSelectionSchemeColor: SchemeColor.primaryContainer,
      inputSelectionOpacity: 0.78,
      inputSelectionHandleSchemeColor: SchemeColor.primaryContainer,
      listTileSelectedSchemeColor: SchemeColor.onTertiary,
      listTileIconSchemeColor: SchemeColor.onSurface,
      listTileTextSchemeColor: SchemeColor.onPrimaryContainer,
      listTileTileSchemeColor: SchemeColor.surfaceContainerLowest,
      listTileSelectedTileSchemeColor: SchemeColor.primary,
      listTileContentPadding: EdgeInsetsDirectional.fromSTEB(13, 4, 6, 4),
      listTileHorizontalTitleGap: 8.0,
      listTileMinVerticalPadding: 5.0,
      listTileStyle: ListTileStyle.drawer,
      listTileTitleAlignment: ListTileTitleAlignment.titleHeight,
      fabUseShape: true,
      fabAlwaysCircular: true,
      fabSchemeColor: SchemeColor.tertiary,
      fabForegroundSchemeColor: SchemeColor.tertiaryContainer,
      chipRadius: 17.0,
      chipFontSize: 11.0,
      chipIconSize: 18.0,
      chipPadding: EdgeInsetsDirectional.fromSTEB(3, 3, 3, 3),
      cardRadius: 5.0,
      popupMenuRadius: 2.0,
      popupMenuElevation: 8.0,
      popupMenuSchemeColor: SchemeColor.surfaceContainerHigh,
      popupMenuOpacity: 0.98,
      alignedDropdown: true,
      tooltipRadius: 16.0,
      dialogElevation: 2.0,
      dialogRadius: 33.0,
      dialogRadiusAdaptive: 8.0,
      useInputDecoratorThemeInDialogs: true,
      timePickerDialogRadius: 3.0,
      timePickerElementRadius: 10.0,
      datePickerDialogRadius: 4.0,
      datePickerHeaderBackgroundSchemeColor: SchemeColor.primary,
      datePickerDividerSchemeColor: SchemeColor.secondary,
      snackBarRadius: 9.0,
      snackBarElevation: 3.0,
      snackBarBackgroundSchemeColor: SchemeColor.onPrimaryContainer,
      snackBarActionSchemeColor: SchemeColor.primaryFixed,
      appBarCenterTitle: true,
      bottomAppBarHeight: 72.0,
      tabBarIndicatorWeight: 6.5,
      tabBarIndicatorTopRadius: 4.5,
      tabBarDividerColor: Color(0x00000000),
      tabBarTabAlignment: TabAlignment.start,
      drawerRadius: 8.0,
      drawerElevation: 4.0,
      drawerBackgroundSchemeColor: SchemeColor.surfaceContainerHighest,
      drawerWidth: 300.0,
      drawerIndicatorWidth: 281.0,
      drawerIndicatorRadius: 10.0,
      drawerIndicatorSchemeColor: SchemeColor.primaryContainer,
      drawerIndicatorOpacity: 0.9,
      drawerSelectedItemSchemeColor: SchemeColor.primary,
      drawerUnselectedItemSchemeColor: SchemeColor.onPrimaryContainer,
      bottomSheetBackgroundColor: SchemeColor.tertiaryContainer,
      bottomSheetModalBackgroundColor: SchemeColor.primaryFixed,
      bottomSheetRadius: 30.0,
      bottomSheetElevation: 4.0,
      bottomSheetModalElevation: 3.0,
      bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.onPrimaryFixed,
      bottomNavigationBarMutedUnselectedLabel: true,
      bottomNavigationBarSelectedIconSchemeColor: SchemeColor.primary,
      bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.onPrimaryFixed,
      bottomNavigationBarMutedUnselectedIcon: true,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.surfaceContainer,
      bottomNavigationBarSelectedLabelSize: 12,
      bottomNavigationBarUnselectedLabelSize: 10,
      bottomNavigationBarSelectedIconSize: 22,
      bottomNavigationBarUnselectedIconSize: 19,
      menuRadius: 7.0,
      menuElevation: 6.0,
      menuSchemeColor: SchemeColor.surfaceContainerHighest,
      menuOpacity: 0.89,
      menuPadding: EdgeInsetsDirectional.fromSTEB(2.0, 3.0, 4.0, 3.0),
      menuBarBackgroundSchemeColor: SchemeColor.tertiary,
      menuBarRadius: 0.0,
      menuBarElevation: 0.0,
      menuBarShadowColor: Color(0x00000000),
      menuItemBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
      menuItemForegroundSchemeColor: SchemeColor.onSurfaceVariant,
      menuIndicatorBackgroundSchemeColor: SchemeColor.secondary,
      searchBarElevation: 2.0,
      searchViewElevation: 2.0,
      searchBarRadius: 5.0,
      searchViewRadius: 5.0,
      searchViewHeaderHeight: 67.0,
      searchUseGlobalShape: true,
      navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      navigationBarUnselectedLabelSchemeColor: SchemeColor.onPrimaryContainer,
      navigationBarMutedUnselectedLabel: true,
      navigationBarSelectedIconSchemeColor: SchemeColor.secondary,
      navigationBarUnselectedIconSchemeColor: SchemeColor.onPrimaryContainer,
      navigationBarMutedUnselectedIcon: true,
      navigationBarIndicatorSchemeColor: SchemeColor.primary,
      navigationBarIndicatorOpacity: 0.76,
      navigationBarIndicatorRadius: 6.0,
      navigationBarBackgroundSchemeColor: SchemeColor.tertiaryFixed,
      navigationBarOpacity: 0.96,
      navigationBarElevation: 8.0,
      navigationBarHeight: 69.0,
      navigationBarLabelBehavior:
          NavigationDestinationLabelBehavior.onlyShowSelected,
      navigationBarSelectedLabelSize: 12,
      navigationBarUnselectedLabelSize: 10,
      navigationBarSelectedIconSize: 25,
      navigationBarUnselectedIconSize: 22,
      navigationRailSelectedLabelSchemeColor: SchemeColor.secondary,
      navigationRailUnselectedLabelSchemeColor: SchemeColor.onPrimaryContainer,
      navigationRailSelectedIconSchemeColor: SchemeColor.secondary,
      navigationRailUnselectedIconSchemeColor: SchemeColor.onPrimaryContainer,
      navigationRailUseIndicator: true,
      navigationRailIndicatorSchemeColor: SchemeColor.primary,
      navigationRailIndicatorOpacity: 0.81,
      navigationRailIndicatorRadius: 9.0,
      navigationRailBackgroundSchemeColor: SchemeColor.primaryFixed,
      navigationRailOpacity: 0.85,
      navigationRailElevation: 9.0,
      navigationRailLabelType: NavigationRailLabelType.all,
      navigationRailSelectedLabelSize: 13,
      navigationRailUnselectedLabelSize: 12,
      navigationRailSelectedIconSize: 22,
      navigationRailUnselectedIconSize: 20,
      navigationRailGroupAlignment: -0.60,
      navigationRailMinWidth: 86,
      navigationRailMinExtendedWidth: 214,
    ),
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
      useError: true,
      useLegacyMonochromeSeedBehavior: true,
    ),
    tones: FlexSchemeVariant.chroma
        .tones(Brightness.dark)
        .higherContrastFixed()
        .monochromeSurfaces()
        .onMainsUseBW()
        .onSurfacesUseBW()
        .surfacesUseBW(),
    visualDensity: VisualDensity.compact,
    materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    swapLegacyOnMaterial3: true,
  );
}
