name: Validate
on:
  pull_request:
    branches: [none]
  push:
    branches: [none]
    paths-ignore:
      - "**.md"
jobs:
  style:
    timeout-minutes: 15
    name: "Analyze code style compliance"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Show Dart SDK version"
        run: dart --version
      - name: "Show Flutter SDK version"
        run: flutter --version
      - name: "Install Flutter package dependencies"
        run: flutter pub get
      - name: "Show outdated packages"
        run: flutter pub outdated
      - name: "Dart Analyzer"
        run: dart analyze . --fatal-infos
      - name: "Formatting Check"
        run: |
          flutter format .
          ./.github/workflows/scripts/validate-formatting.sh
  test:
    runs-on: ubuntu-latest
    name: "Tests and coverage"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Test package FlexColorScheme with coverage"
        run: flutter test --coverage
      - name: "Upload test coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
